### ISSUE TITLE
Don't work with Langify app

### ISSUE THREAD

**Issue by cristianurbano** [culturekings/shopify-shortcodes#10]
Hello!

shopify-shortcodes does not work with [langigy app](https://apps.shopify.com/langify).

Any idea?

**Comment by cristianurbano** [comment]
I found the solution, in order to work with langify we need to change 

`{% include 'shortcode' load: page.content %}`

to:

`{% include 'ly-content' with page %}`
`{% include 'shortcode' load: ly_translation %}`

**Comment by Cam** [comment]
Good one. Useful to know!
