### ISSUE TITLE
render does not work unless i modify it to following

### ISSUE THREAD

**Issue by malipetek** [culturekings/shopify-shortcodes#14]
```
{%- assign shortcodekeyfound = false -%}

    {%- for key in variable  -%}

        {%- assign keyname = key | split: '=' -%}

        {%- if keyname.first == render -%}

     {%- assign shortcodekeyfound = true -%}

    {{ keyname[1] | replace: "'", "" }}

    {%- endif -%}

{%- endfor -%}

{%- if shortcodekeyfound == false -%}

    {{-default-}}

{%- endif -%} 
```
Do you thinks its because of my modifications on my theme?

**Comment by malipetek** [comment]
it was because i did something like this in product template, i was including shortcode load this way:
 `{% section 'product' %}`,
 and then i did:
 `{% capture productSection} {%section 'product' %} {% endcapture %} {% include 'shortcode' load: productSection %}`. 
And i guess this is not valid.

**Comment by keithpickering** [comment]
Thanks for the modified code! Whether or not it's valid according to the original intent of the plugin, it works.
